import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "slop-loader Next.js Example",
  description: "Generated by slop-loader and create-next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
